#!/usr/bin/env node
/**
 * Content queue tracker. Scans src/content/dossiers/*.mdx, parses
 * frontmatter, and generates CONTENT-QUEUE.md grouping each guide
 * by status (published, scheduled, draft). Run manually:
 *
 *   pnpm queue
 *
 * The "Planned" section is hand-maintained between the markers
 *   <!-- planned:start -->
 *   <!-- planned:end -->
 * and preserved across regenerations.
 *
 * Categorization (mirrors src/pages/guides/[slug].astro + astro.config.mjs):
 *   - draft: true                            → Drafts (excluded from build)
 *   - datePublished <= TODAY (ISO UTC date)  → Published (live, in sitemap)
 *   - datePublished > TODAY                  → Scheduled (drip queue)
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '..');
const GUIDES_DIR = path.join(ROOT, 'src/content/dossiers');
const QUEUE_FILE = path.join(ROOT, 'CONTENT-QUEUE.md');

const TODAY = new Date().toISOString().slice(0, 10);

const PLANNED_DEFAULT = `
_Aucun guide prévu non écrit pour le moment. Liste à compléter à la main entre les marqueurs ci-dessus._
`;

function field(content, key) {
  const m = content.match(new RegExp(`^${key}:\\s*(.+?)\\s*$`, 'm'));
  if (!m) return null;
  let v = m[1].trim();
  // Strip a single pair of surrounding quotes (values may contain apostrophes).
  if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
    v = v.slice(1, -1);
  }
  return v;
}

function bool(content, key) {
  const m = content.match(new RegExp(`^${key}:\\s*(true|false)\\s*$`, 'm'));
  return m ? m[1] === 'true' : false;
}

const files = fs.readdirSync(GUIDES_DIR).filter((f) => f.endsWith('.mdx') || f.endsWith('.md'));

const articles = files.map((f) => {
  const content = fs.readFileSync(path.join(GUIDES_DIR, f), 'utf-8');
  return {
    file: f,
    slug: f.replace(/\.mdx?$/, ''),
    title: field(content, 'title') || '(no title)',
    hub: field(content, 'hub') || '—',
    datePublished: field(content, 'datePublished') || '—',
    dateModified: field(content, 'dateModified') || '—',
    draft: bool(content, 'draft'),
  };
});

const drafts = articles
  .filter((a) => a.draft)
  .sort((a, b) => a.slug.localeCompare(b.slug));

const published = articles
  .filter((a) => !a.draft && a.datePublished !== '—' && a.datePublished <= TODAY)
  .sort((a, b) => b.datePublished.localeCompare(a.datePublished));

const scheduled = articles
  .filter((a) => !a.draft && a.datePublished !== '—' && a.datePublished > TODAY)
  .sort((a, b) => a.datePublished.localeCompare(b.datePublished));

// Preserve the human-edited Planned section across regenerations.
let plannedSection = PLANNED_DEFAULT;
if (fs.existsSync(QUEUE_FILE)) {
  const existing = fs.readFileSync(QUEUE_FILE, 'utf-8');
  const m = existing.match(/<!-- planned:start -->([\s\S]*?)<!-- planned:end -->/);
  if (m) plannedSection = m[1];
}

function tableRow(a) {
  return `| ${a.datePublished} | [${a.title}](src/content/dossiers/${a.file}) | ${a.hub} |`;
}

function tableOrPlaceholder(rows, placeholder) {
  return rows.length ? rows.map(tableRow).join('\n') : placeholder;
}

const out = `# Content Queue

Auto-generated by \`scripts/content-queue.mjs\`. Run \`pnpm queue\` to refresh
after adding, editing, or rescheduling a guide.

The **Planned** section between the HTML comment markers is hand-maintained
and preserved across regenerations — list there what you intend to write
but haven't started yet. Everything below it is derived from the MDX
frontmatter of \`src/content/dossiers/*.mdx\`.

- **Today**: ${TODAY}
- **Published**: ${published.length}
- **Scheduled (drip queue)**: ${scheduled.length}
- **Drafts**: ${drafts.length}
- **Total tracked articles**: ${articles.length}

## Planned (not yet written)
<!-- planned:start -->${plannedSection}<!-- planned:end -->

## Scheduled — datePublished in the future (drip queue)

${
  scheduled.length
    ? `| Date | Title | Hub |
|---|---|---|
${tableOrPlaceholder(scheduled, '')}`
    : '_Aucun guide programmé._'
}

## Published — live on the site

${
  published.length
    ? `| Date | Title | Hub |
|---|---|---|
${tableOrPlaceholder(published, '')}`
    : '_Aucun guide publié pour le moment._'
}

## Drafts — \`draft: true\`, excluded from build

${
  drafts.length
    ? drafts
        .map((a) => `- [${a.slug}](src/content/dossiers/${a.file}) — ${a.title}`)
        .join('\n')
    : '_Aucun brouillon._'
}
`;

fs.writeFileSync(QUEUE_FILE, out);

const yellow = (s) => `\x1b[33m${s}\x1b[0m`;
const green = (s) => `\x1b[32m${s}\x1b[0m`;
const dim = (s) => `\x1b[2m${s}\x1b[0m`;

console.log(`Content queue — ${TODAY}`);
console.log(
  `  ${green(`${published.length} published`)}  ${yellow(`${scheduled.length} scheduled`)}  ${dim(`${drafts.length} drafts`)}`,
);
if (scheduled.length) {
  console.log(`\nNext drip publications:`);
  for (const a of scheduled.slice(0, 5)) {
    console.log(`  ${a.datePublished}  ${a.title}`);
  }
  if (scheduled.length > 5) console.log(`  ${dim(`… and ${scheduled.length - 5} more.`)}`);
}
console.log(`\nWrote ${path.relative(ROOT, QUEUE_FILE)}.`);
